## Basics Functions

In [3]:
import numpy as np
array1 = np.array([[3,2,5,7,0], [1,12,3,4,5]]) # 2D array
print(array1)

[[ 3  2  5  7  0]
 [ 1 12  3  4  5]]


In [12]:
array1.shape

(2, 5)

In [13]:
array1.dtype

dtype('int32')

In [14]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(6).dtype

dtype('float64')

In [16]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
array1 *array1

array([[  9,   4,  25,  49,   0],
       [  1, 144,   9,  16,  25]])

## Slicing

In [4]:
array2 = np.array([5,4,64,3,3,3])

In [5]:
array2[4:6]

array([3, 3])

In [6]:
arr = array2[4:6]

In [7]:
arr

array([3, 3])

In [8]:
arr[0] = 9 # changing "arr" array

In [9]:
array2 # array2 is changed, older or original array is changing instaed of "arr".
# because of pointers, numpy uses 'C' language.

array([ 5,  4, 64,  3,  9,  3])

In [10]:
#to prevent this use .copy()
array2 = np.array([5,4,64,3,3,3]).copy()

In [11]:
array1

array([[ 3,  2,  5,  7,  0],
       [ 1, 12,  3,  4,  5]])