In [5]:
import numpy as np
array1 = np.array([[3,2,5,7,0], [1,12,3,4,5]])
print(array1)

[[ 3  2  5  7  0]
 [ 1 12  3  4  5]]


In [12]:
array1.shape

(2, 5)

In [13]:
array1.dtype

dtype('int32')

In [14]:
np.zeros((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [15]:
np.ones(6).dtype

dtype('float64')

In [16]:
np.empty((4,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [6]:
array1 *array1

array([[  9,   4,  25,  49,   0],
       [  1, 144,   9,  16,  25]])